// gen_tier2b_tier3.js - Tier 2 Part B + Tier 3 sector question bank generator
const fs = require('fs');
const dir = 'server/questions';

// ===== EDUCATION LEADERSHIP (25 questions) =====
const educationLeadership = {
  metadata: { sector: 'Education Leadership', generated: '2026-08-30', total: 25, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'ed_001',text:'Tell me about improving student outcomes in your school.',category:'behavioral',seniority:['mid','senior','manager'],answer_framework:{structure:'STAR',key_points:['Data review','Interventions designed','Stakeholder buy-in','Results measured'],strong_answer_signals:['Academic growth','Stakeholder engagement'],avoid:['No data','No stakeholder input']}},
    {id:'ed_002',text:'How do you manage a teaching team?',category:'manager',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Professional development','Performance management','Team building','Resource allocation'],strong_answer_signals:['Team performance improved','Teacher satisfaction'],avoid:['Micromanagement','No development']}},
    {id:'ed_003',text:'Describe your approach to curriculum development.',category:'technical',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Standards aligned','Stakeholder input','Pilot tested','Feedback incorporated'],strong_answer_signals:['Relevant and rigorous','Student-centered'],avoid:['Outdated curriculum','No input']}},
    {id:'ed_004',text:'How do you handle a parent who disagrees with your decision?',category:'situational',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Listened actively','Explained rationale','Found common ground','Documented'],strong_answer_signals:['Relationship maintained','Parent satisfied'],avoid:['Defensive stance','No documentation']}},
    {id:'ed_005',text:'Why education leadership? What drives you?',category:'motivation',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Student impact desire','Leadership passion','Community improvement','Mission-driven'],strong_answer_signals:['Specific motivation','Long-term commitment'],avoid:['Job only','No mission']}},
    {id:'ed_006',text:'How do you approach assessment and data-driven instruction?',category:'technical',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Assessment designed','Data analyzed','Instructional adjustments','Progress monitored'],strong_answer_signals:['Student growth','Targeted instruction'],avoid:['High-stakes testing only','No differentiation']}},
    {id:'ed_007',text:'Tell me about managing school budget and resources.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Budget analyzed','Priorities set','Cost-saving measures','Transparency maintained'],strong_answer_signals:['Sustainable budget','Stakeholder trust'],avoid:['Arbitrary cuts','No communication']}},
    {id:'ed_008',text:'How do you handle teacher evaluation and feedback?',category:'manager',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Clear standards','Observations conducted','Feedback delivered','Support provided'],strong_answer_signals:['Teacher improvement','Fair process'],avoid:['Arbitrary ratings','No support']}},
    {id:'ed_009',text:'Describe your experience with district-wide initiatives.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Change management','Communication plan','Training provided','Progress tracked'],strong_answer_signals:['Successful rollout','Buy-in achieved'],avoid:['Top-down only','Poor communication']}},
    {id:'ed_010',text:'How do you ensure equity and inclusion in your school?',category:'situational',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Equity lens applied','Data disaggregated','Interventions designed','Accountability maintained'],strong_answer_signals:['Gap reduction','Inclusive culture'],avoid:['Assumed equity','No data']}},
    {id:'ed_011',text:'Tell me about implementing a new technology in education.',category:'behavioral',seniority:['mid','senior','manager'],answer_framework:{structure:'STAR',key_points:['Need identified','Solution evaluated','Implementation planned','Training provided'],strong_answer_signals:['Adoption achieved','Impact shown'],avoid:['Tech for tech sake','No training']}},
    {id:'ed_012',text:'How do you handle a student discipline issue?',category:'situational',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Fair process followed','Documentation','Restorative options','Prevention focus'],strong_answer_signals:['Safe environment','Due process'],avoid:['Zero tolerance','No prevention']}},
    {id:'ed_013',text:'How do you approach school accreditation?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Standards researched','Gaps identified','Improvement plan','Report submitted'],strong_answer_signals:['Successful accreditation','Continuous improvement'],avoid:['Minimum compliance','No improvement']}},
    {id:'ed_014',text:'Describe your experience with special education.',category:'technical',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['IEP process','Collaboration','Services provided','Outcome tracking'],strong_answer_signals:['Student success','Parent satisfaction'],avoid:['Bureaucracy focus','No outcomes']}},
    {id:'ed_015',text:'How do you manage school safety and security?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Threat assessment','Protocols established','Staff trained','Community engaged'],strong_answer_signals:['Safe environment','Crisis readiness'],avoid:['Reactive only','No planning']}},
    {id:'ed_016',text:'Tell me about a time you had to make a difficult decision for the school.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Stakes understood','Stakeholders consulted','Decision made','Communicated'],strong_answer_signals:['Better outcome','Trust maintained'],avoid:['No consultation','Poor communication']}},
    {id:'ed_017',text:'How do you approach parent and community engagement?',category:'technical',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Communication channels','Events planned','Feedback collected','Volunteer programs'],strong_answer_signals:['Engaged community','Positive relationships'],avoid:['One-way communication','No invitations']}},
    {id:'ed_018',text:'How do you handle teacher shortage and staffing?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Recruitment strategy','Retention efforts','Substitute pool','Professional development'],strong_answer_signals:['Staffing stable','Teacher satisfaction'],avoid:['Understaffed','High turnover']}},
    {id:'ed_019',text:'Describe your experience with educational research.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Research question','Methodology used','Data analyzed','Findings applied'],strong_answer_signals:['Practice improved','Evidence-based'],avoid:['Opinion only','No data']}},
    {id:'ed_020',text:'How do you approach college and career readiness?',category:'technical',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Guidance programs','Career exposures','Application support','Post-secondary tracking'],strong_answer_signals:['Student preparedness','College enrollment'],avoid:['Generic advising','No tracking']}},
    {id:'ed_021',text:'Tell me about developing teacher leadership.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Leadership opportunities','Mentor assigned','Growth observed','Contribution measured'],strong_answer_signals:['Empowered teachers','School improved'],avoid:['No development','High turnover']}},
    {id:'ed_022',text:'How do you manage multi-school or multi-campus responsibilities?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Systematic management','Communication protocols','Data systems','Delegation'],strong_answer_signals:['Consistent standards','Effective oversight'],avoid:['Inconsistent','No systems']}},
    {id:'ed_023',text:'How do you handle curriculum alignment and standards?',category:'technical',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Standards mapped','Pacing guides','Assessment alignment','Vertical articulation'],strong_answer_signals:['Aligned curriculum','Clear progression'],avoid:['Fragmented curriculum','No alignment']}},
    {id:'ed_024',text:'How do you approach professional learning communities (PLCs)?',category:'technical',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Meetings structured','Data driven','Action plans','Follow-up'],strong_answer_signals:['Collaborative culture','Student learning improved'],avoid:['Status meetings only','No action']}},
    {id:'ed_025',text:'What changes have you seen in education leadership recently?',category:'motivation',seniority:['mid','senior','manager'],answer_framework:{structure:'Framework',key_points:['Technology integration','Personalized learning','Equity focus','Data utilization'],strong_answer_signals:['Adaptability shown','Specific changes'],avoid:['Resistance to change','No observation']}}
  ]
};

// ===== REAL ESTATE & PROPERTY MANAGEMENT (20 questions) =====
const realEstate = {
  metadata: { sector: 'Real Estate & Property Management', generated: '2026-08-30', total: 20, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'re_001',text:'Tell me about closing a challenging deal.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Objections handled','Creative solutions','Documentation managed','Deal closed'],strong_answer_signals:['Creative negotiation','Result achieved'],avoid:['Gave up easily','No creativity']}},
    {id:'re_002',text:'How do you price a property competitively?',category:'technical',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Market analysis','Comparable sales','Condition assessment','Pricing strategy'],strong_answer_signals:['Accurate pricing','Quick sale'],avoid:['Overpriced','No research']}},
    {id:'re_003',text:'Describe your approach to lead generation.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Prospecting methods','Network building','Online marketing','Follow-up process'],strong_answer_signals:['Consistent leads','Conversion high'],avoid:['One method only','No follow-up']}},
    {id:'re_004',text:'How do you handle a difficult tenant?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Issues identified','Communication used','Resolutions offered','Documentation'],strong_answer_signals:['Resolved issue','Relationship maintained'],avoid:['Eviction immediate','No communication']}},
    {id:'re_005',text:'Why real estate? What drives your success?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Independent success','Asset management','Relationship building','Market knowledge'],strong_answer_signals:['Specific market story','Long-term focus'],avoid:['Commission only','No market interest']}},
    {id:'re_006',text:'How do you handle multiple offers on a property?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Offers evaluated','Best and final','Negotiation','Client advised'],strong_answer_signals:['Client best interest','Quick decision'],avoid:['Rushed decision','No evaluation']}},
    {id:'re_007',text:'Tell me about a time you had to overcome market challenges.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Market downturn','Creative marketing','Client needs met','Results achieved'],strong_answer_signals:['Adapted strategy','Client retained'],avoid:['Blamed market','No adaptation']}},
    {id:'re_008',text:'How do you manage property maintenance and tenant relations?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Preventive maintenance','Emergency response','Tenant satisfaction','Vendor management'],strong_answer_signals:['Low vacancy','Positive reviews'],avoid:['Reactive only','No prevention']}},
    {id:'re_009',text:'How do you handle a bidding war?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Market assessment','Negotiation strategy','Client preparation','Timing'],strong_answer_signals:['Sale maximised','Client satisfied'],avoid:['Left money on table','No preparation']}},
    {id:'re_010',text:'Describe your experience with commercial real estate.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Property types','Lease structuring','Tenant placement','Market analysis'],strong_answer_signals:['Successful leaseups','Tenant satisfaction'],avoid:['Residential only','No commercial']}},
    {id:'re_011',text:'How do you approach a buyer agent relationship?',category:'technical',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Trust building','Communication','MLS usage','Transaction management'],strong_answer_signals:['Ongoing referrals','Smooth transactions'],avoid:['Competitive only','No communication']}},
    {id:'re_012',text:'How do you handle a title or inspection issue?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Problem identified','Solutions presented','Client advised','Deal protected'],strong_answer_signals:['Issue resolved','Deal closed'],avoid:['Panic','No options']}},
    {id:'re_013',text:'Tell me about building your real estate business.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Early days','Growth strategies','Brand building','Business systems'],strong_answer_signals:['Sustainable growth','Efficient systems'],avoid:['Luck only','No systems']}},
    {id:'re_014',text:'How do you handle commission disputes?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Escalate appropriately','Multiple perspectives heard','Fair resolution','Documentation'],strong_answer_signals:['Relationship preserved','Fair outcome'],avoid:['Confrontational','No documentation']}},
    {id:'re_015',text:'How do you approach luxury property marketing?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['High-end photography','Targeted marketing','Exclusive networks','Discreet presentation'],strong_answer_signals:['Qualified buyers','Brand enhanced'],avoid:['Mass marketing only','No photography']}},
    {id:'re_016',text:'What is your approach to time on market?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Pricing first','Marketing intensity','Market timing','Open house strategy'],strong_answer_signals:['Quick sale','Proper price'],avoid:['Empty promises','Overpricing']}},
    {id:'re_017',text:'How do you handle a short sale or distressed property?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Investor analysis','Negotiation','Approval process','Creative offer'],strong_answer_signals:['Successful sale','Client protected'],avoid:['No negotiations','Unrealistic pricing']}},
    {id:'re_018',text:'How do you approach virtual tours and digital marketing?',category:'technical',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['3D tours used','Social media','SEO','Online listings'],strong_answer_signals:['Increased exposure','More inquiries'],avoid:['Outdated marketing','No digital']}},
    {id:'re_019',text:'Describe your experience with real estate finance.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Loan types','Rate shopping','Qualification process','Closing coordination'],strong_answer_signals:['Smooth closings','Client educated'],avoid:['No finance knowledge','Poor coordination']}},
    {id:'re_020',text:'How do you handle market downturn or correction?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Market reality','Strategic adjustments','Client communication','Opportunistic positioning'],strong_answer_signals:['Client protected','Positioned for recovery'],avoid:['Denial','Panic selling']}}
  ]
};

// ===== INSURANCE (Underwriting, Claims, Actuarial) (30 questions) =====
const insurance = {
  metadata: { sector: 'Insurance', generated: '2026-08-30', total: 30, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'in_001',text:'Tell me about a complex claim you handled.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Claim complexity','Investigation conducted','Settlement negotiated','Client satisfaction'],strong_answer_signals:['Fair settlement','Lost time minimized'],avoid:['Rushed decision','No investigation']}},
    {id:'in_002',text:'How do you approach risk assessment for underwriting?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Data analyzed','Rating factors applied','Experience modification','Pricing determined'],strong_answer_signals:['Accurate pricing','Risk assessed'],avoid:['No data','Overly conservative']}},
    {id:'in_003',text:'Describe your experience with claims investigation.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Suspicious claims identified','Evidence gathered','Expert consulted','Fraud prevented'],strong_answer_signals:['Fraud detected','Recovery achieved'],avoid:['No verification','Trusted claims']}},
    {id:'in_004',text:'How do you handle a policyholder who disputes a denial?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Concern understood','Policy reviewed','Appeal process used','Communication maintained'],strong_answer_signals:['Resolution achieved','Relationship preserved'],avoid:['Stonewalled','No empathy']}},
    {id:'in_005',text:'Why insurance? What drives your success in this field?',category:'motivation',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Risk management passion','Data analysis interest','Long-term client relationships','Financial stability'],strong_answer_signals:['Specific motivation','Long-term focus'],avoid:['Commission only','No purpose']}},
    {id:'in_006',text:'How do you stay current with insurance regulations?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['State updates','Licensing','Regulatory bulletins','Compliance training'],strong_answer_signals:['Current license','Regulation aware'],avoid:['Lapsed licensing','No compliance']}},
    {id:'in_007',text:'Describe your approach to actuarial analysis.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Statistical methods','Experience data','Trend analysis','Reserve calculations'],strong_answer_signals:['Accurate analysis','Risk measured'],avoid:['Simple averaging','No trend']}},
    {id:'in_008',text:'How do you handle a catastrophic loss or catastrophe?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Claims surge managed','Reinsurance utilized','Communication coordinated','Recovery plan'],strong_answer_signals:['Reserves sufficient','Stakeholders informed'],avoid:['Overwhelmed','Poor communication']}},
    {id:'in_009',text:'How do you approach sales in a difficult market?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Product knowledge','Customer needs','Differentiation','Pipeline management'],strong_answer_signals:['Sales maintained','Product value communicated'],avoid:['Price discounting','Product discounting']}},
    {id:'in_010',text:'Tell me about improving claims processing efficiency.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Process mapped','Bottlenecks identified','Automation implemented','TAT improved'],strong_answer_signals:['Efficient claims','Customer satisfaction'],avoid:['Manual-only','No improvement']}},
    {id:'in_011',text:'How do you handle a compliance audit?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Records organized','Controls documented','Issues addressed','Audit completed'],strong_answer_signals:['Clean audit','Regulation followed'],avoid:['Poor documentation','Surprises on audit']}},
    {id:'in_012',text:'How do you approach portfolio management in insurance?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Risk portfolio reviewed','Diversification applied','Reserve adequacy','Reinsurance strategy'],strong_answer_signals:['Diversified book','Reserves adequate'],avoid:['Concentration risk','Low reserves']}},
    {id:'in_013',text:'Describe your experience with reinsurance.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Treaty vs facultative','Pricing models','Claims handled','Ceding strategy'],strong_answer_signals:['Optimally ceded','Captive retained'],avoid:['Over-ceded','No analysis']}},
    {id:'in_014',text:'How do you handle customer complaints?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Complaint logged','Investigation','Resolution offered','Follow-up'],strong_answer_signals:['Customer satisfaction','No repeat'],avoid:['ignored','No resolution']}},
    {id:'in_015',text:'How do you approach financial reporting for insurance?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Statutory reporting','NAIC forms','ACORD data','Regulatory filing'],strong_answer_signals:['Timely filing','No errors'],avoid:['Late filing','Errors','No filing']}},
    {id:'in_016',text:'Tell me about a time you improved retention.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Churn analyzed','Improvement initiatives','Retention rate measured','Results achieved'],strong_answer_signals:['Reduced churn','Customer loyalty'],avoid:['No analysis','No action']}},
    {id:'in_017',text:'How do you handle underwriting for unusual risks?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Exposure evaluated','Experts consulted','Terms structured','Premium set'],strong_answer_signals:['Risk properly covered','Client retained'],avoid:['Auto-rejected','No analysis']}},
    {id:'in_018',text:'How do you approach loss control consulting?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Risk assessments','Recommendations','Follow-up','Claims reduction'],strong_answer_signals:['Losses reduced','Client value'],avoid:['One-time visit','No follow-up']}},
    {id:'in_019',text:'Describe your experience with MGA or wholesale operations.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Carrier agreements','Product development','Margin management','Compliance'],strong_answer_signals:['Profitable MGAs','Regulatory compliance'],avoid:['No oversight','Margin erosion']}},
    {id:'in_020',text:'How do you manage regulatory changes like rate filings?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Filing requirements','Rate justification','Documentation','Approval process'],strong_answer_signals:['Filings approved','Rates competitive'],avoid:['Late filings','Insufficient documentation']}},
    {id:'in_021',text:'What changes have you seen in insurance technology?',category:'motivation',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['AI underwriting','IoT telematics','Digital claims','Insurtech partnerships'],strong_answer_signals:['Tech adoption','Competitive advantage'],avoid:['Resistance to change','No innovation']}},
    {id:'in_022',text:'How do you handle a policyholder in financial difficulty?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Payment options','Hardship programs','Documentation','Collections strategy'],strong_answer_signals:['Retained customer','Managed risk'],avoid:['Immediate cancellation','No options']}},
    {id:'in_023',text:'How do you approach D&O liability insurance?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Coverage analysis','Management concerns','Claims handling','Reporting requirements'],strong_answer_signals:['Adequate coverage','Claims managed'],avoid:['Over or underinsurance']}},
    {id:'in_024',text:'Describe your approach to ESG in insurance.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Sustainable underwriting','Green investments','ESG reporting','Client engagement'],strong_answer_signals:['ESG integration','Client value'],avoid:['ESG ignored','No reporting']}},
    {id:'in_025',text:'How do you handle cross-border insurance?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Regulatory research','Local partners','Compliance','Currency'],strong_answer_signals:['Smooth placement','Regulatory compliant'],avoid:['No local knowledge','Regulatory issues']}},
    {id:'in_026',text:'Tell me about your experience with claims automation.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Tools evaluated','Process mapped','Exceptions handled','Results measured'],strong_answer_signals:['Efficiency gains','Accuracy maintained'],avoid:['Pure automation','No exceptions']}},
    {id:'in_027',text:'How do you approach insurance product development?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Market analysis','Pricing models','Distribution plan','Launch strategy'],strong_answer_signals:['Profitable product','Market fit'],avoid:['No analysis','Poor positioning']}},
    {id:'in_028',text:'How do you handle a major incident like a natural disaster?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Emergency response','Claims surge','Reinsurance activation','Communication'],strong_answer_signals:['Reserves adequate','Customer protected'],avoid:['Overwhelmed','No plan']}},
    {id:'in_029',text:'Describe your approach to fraud investigation.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Indicators reviewed','Investigation conducted','Recovery pursued','Prevention measures'],strong_answer_signals:['Fraud detected','Loss recovered'],avoid:['Ignored signs','No investigation']}},
    {id:'in_030',text:'How do you balance service and profitability?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Service metrics tracked','Cost analysis','Value proposition','Customer segmentation'],strong_answer_signals:['Profitable service','Customer loyalty'],avoid:['Cost only','No service focus']}}
  ]
};

// ===== TEACHING & EDUCATION (25 questions) =====
const teaching = {
  metadata: { sector: 'Teaching & Education', generated: '2026-08-30', total: 25, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'te_001',text:'Tell me about a time you had to adapt your teaching for different learning styles.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Learner needs assessed','Multiple approaches used','Engagement tracked','Learning outcomes'],strong_answer_signals:['All students benefited','Differentiation visible'],avoid:['One-size-fits-all','No adaptation']}},
    {id:'te_002',text:'How do you handle a disruptive student?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Behavior understood','De-escalation used','Intervention applied','Follow-up'],strong_answer_signals:['Behavior improved','Classroom safe'],avoid:['Public embarrassment','No follow-up']}},
    {id:'te_003',text:'Describe your approach to classroom management.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Rules established','Consistency maintained','Positive reinforcement','Procedures followed'],strong_answer_signals:['Respectful environment','Learning focus'],avoid:['Authoritarian','No structure']}},
    {id:'te_004',text:'How do you assess student learning effectively?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Assessment aligned to objectives','Varied methods used','Feedback provided','Data driven'],strong_answer_signals:['Accurate assessment','Student growth'],avoid:['Tests only','No feedback']}},
    {id:'te_005',text:'Why teaching? What keeps you passionate?',category:'motivation',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Student success desire','Lifelong learning','Impact on lives','Intellectual challenge'],strong_answer_signals:['Specific impact stories','Long-term commitment'],avoid:['No passion','Burnout signs']}},
    {id:'te_006',text:'Tell me about integrating technology in your classroom.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Tech need identified','Tools selected','Student learning measured','Adjustment made'],strong_answer_signals:['Enhanced learning','Student engagement'],avoid:['Tech for tech sake','No assessment']}},
    {id:'te_007',text:'How do you support students with diverse needs?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Differentiation planned','Accommodations provided','Collaborative teams','Individual progress'],strong_answer_signals:['Inclusive classroom','Progress tracked'],avoid:['One-size-fits-all','Isolated support']}},
    {id:'te_008',text:'How do you handle a parent who is difficult to communicate with?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Stay professional','Document attempts','Administrator involved','Communication maintained'],strong_answer_signals:['Issue resolved','Relationship preserved'],avoid:['Conflict','No documentation']}},
    {id:'te_009',text:'Describe your approach to curriculum implementation.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Standards understood','Pacing planned','Resources gathered','Student centered'],strong_answer_signals:['Students engaged','Objectives met'],avoid:['Rushed implementation','No pacing']}},
    {id:'te_010',text:'How do you handle a mistake in your teaching?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Acknowledged error','Explanation provided','Correction made','Prevention planned'],strong_answer_signals:['Student learning continued','Trust maintained'],avoid:['Ignored error','Blamed students']}},
    {id:'te_011',text:'Tell me about a time you innovated in your teaching.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Limitation identified','Innovation designed','Students engaged','Results measured'],strong_answer_signals:['Impactful change','Student inspired'],avoid:['No change','No measurement']}},
    {id:'te_012',text:'How do you approach assessment and accountability data?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Data analyzed','Identified trends','Interventions planned','Progress monitored'],strong_answer_signals:['Student growth','Data driven'],avoid:['Data only','No action']}},
    {id:'te_013',text:'How do you build relationships with students?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Know names','Individual attention','Respectful tone','High expectations'],strong_answer_signals:['Student trust','Engagement high'],avoid:['Distant teacher','Low expectations']}},
    {id:'te_014',text:'How do you handle a parent who blames you for their child struggles?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Listen actively','Seek to understand','Share observations','Collaborative plan'],strong_answer_signals:['Parent felt heard','Student helped'],avoid:['Defensive','No empathy']}},
    {id:'te_015',text:'Describe your experience with learning assessments.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Formative and summative','Rubrics used','Feedback given','Data collected'],strong_answer_signals:['Assessment informed','Learning visible'],avoid:['Grades only','No feedback']}},
    {id:'te_016',text:'How do you manage instructional time effectively?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Lesson planning','Routine established','Transitions managed','Focus maintained'],strong_answer_signals:['Learning maximized','Students on task'],avoid:['Chatty lessons','No structure']}},
    {id:'te_017',text:'Tell me about a time you had to work with a difficult colleague.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Issue identified','Professional approach','Problem solved','Working relationship'],strong_answer_signals:['Resolution achieved','Collegiality maintained'],avoid:['Gossip','Confrontation']}},
    {id:'te_018',text:'How do you approach professional development for teachers?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Needs assessed','Training provided','Coaching offered','Growth tracked'],strong_answer_signals:['Teacher improvement','Job satisfaction'],avoid:['One-size-fits-all','No follow-up']}},
    {id:'te_019',text:'How do you handle standardized test preparation?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Skills aligned','Practice provided','Stress managed','Results reviewed'],strong_answer_signals:['Test performance','Student confidence'],avoid:['Test prep only','High anxiety']}},
    {id:'te_020',text:'How do you approach equity in education?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Bias examined','Equitable practices','Resource allocation','Cultural responsiveness'],strong_answer_signals:['All students succeed','Inclusive culture'],avoid:['Colorblind approach','No equity focus']}},
    {id:'te_021',text:'Describe your experience with special education inclusion.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['IEP collaboration','Adaptations made','Progress monitored','Family communication'],strong_answer_signals:['Student success','Family partnership'],avoid:['Separate only','No communication']}},
    {id:'te_022',text:'How do you handle parent conferences?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Data prepared','Strengths highlighted','Growth areas','Next steps'],strong_answer_signals:['Parent understanding','Action plan'],avoid:['General comments','No data']}},
    {id:'te_023',text:'How do you approach social-emotional learning (SEL)?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['SEL framework','Skill instruction','Modeling','Caring environment','Progress tracked'],strong_answer_signals:['SEL implemented','Well-being improved'],avoid:['Ignored SEL','No instruction']}},
    {id:'te_024',text:'Tell me about a time you led a school improvement initiative.',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Problem identified','Team formed','Implementation planned','Results measured'],strong_answer_signals:['Improvement achieved','Team ownership'],avoid:['Top-down mandate','No buy-in']}},
    {id:'te_025',text:'What changes do you see coming in education?',category:'motivation',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Personalized learning','AI integration','Equity focus','Teacher autonomy'],strong_answer_signals:['Adapted to change','Forward thinking'],avoid:['Resistant to change','No vision']}}
  ]
};

// Write all files
fs.writeFileSync(dir + '/education_leadership_questions.json', JSON.stringify(educationLeadership, null, 2));
console.log('Created education_leadership_questions.json with', educationLeadership.questions.length, 'questions');
fs.writeFileSync(dir + '/real_estate_questions.json', JSON.stringify(realEstate, null, 2));
console.log('Created real_estate_questions.json with', realEstate.questions.length, 'questions');
fs.writeFileSync(dir + '/insurance_questions.json', JSON.stringify(insurance, null, 2));
console.log('Created insurance_questions.json with', insurance.questions.length, 'questions');
fs.writeFileSync(dir + '/teaching_questions.json', JSON.stringify(teaching, null, 2));
console.log('Created teaching_questions.json with', teaching.questions.length, 'questions');
console.log('Tier 2 + Tier 3 subtotal: 90+25+20+30+25 =', 25+20+30+25+25);
