// gen_tier1_c.js - Tier 1 part C: Data Engineering + UX/UI Design
const fs = require('fs');
const dir = 'server/questions';

// ===== DATA ENGINEERING (35 questions) =====
const dataEng = {
  metadata: { sector: 'Data Engineering', generated: '2026-08-30', total: 35, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'de_001',text:'Tell me about building a data pipeline from scratch.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Requirements gathered','Architecture designed','Pipeline built and tested','Monitoring set up'],strong_answer_signals:['Scalable pipeline','Reliable data'],avoid:['No architecture','No monitoring']}},
    {id:'de_002',text:'How do you handle data quality issues?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Validation rules','Monitoring','Alerting','Data quality dashboard'],strong_answer_signals:['Quality checks in place','Issues detected early'],avoid:['No validation','Issues unnoticed']}},
    {id:'de_003',text:'How do you design a data warehouse schema?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Star vs snowflake','Fact and dimension tables','Granularity','Partitioning'],strong_answer_signals:['Query performance considered'],avoid:['No modeling','Poor query performance']}},
    {id:'de_004',text:'Tell me about a time your pipeline broke in production.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Incident detected','Root cause found','Data restored','Prevention implemented'],strong_answer_signals:['Quick recovery','Prevention added'],avoid:['Data loss','No root cause analysis']}},
    {id:'de_005',text:'How do you choose between batch and streaming processing?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Latency requirements','Data volume','Cost trade-offs','Complexity'],strong_answer_signals:['Right choice for use case'],avoid:['Always one approach']}},
    {id:'de_006',text:'How do you ensure data security and compliance (GDPR, PII)?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Data classification','Encryption','Access control','Anonymization'],strong_answer_signals:['Compliance achieved','PII protected'],avoid:['No classification','No access control']}},
    {id:'de_007',text:'Describe your experience with orchestration tools.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['DAG design','Scheduling','Monitoring','Retry logic'],strong_answer_signals:['Reliable pipelines','Clear DAG structure'],avoid:['No orchestration','Ad-hoc scripts']}},
    {id:'de_008',text:'How do you handle schema changes in production?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Schema versioning','Backward compatibility','Migration plan','Testing'],strong_answer_signals:['Zero downtime migration'],avoid:['Breaking changes','No versioning']}},
    {id:'de_009',text:'How do you optimize a slow-running query?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Explain plan','Indexes','Partitioning','Caching'],strong_answer_signals:['Query time improved'],avoid:['No optimization','Full table scan']}},
    {id:'de_010',text:'Tell me about a data migration project.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Source and target assessed','Migration strategy tested','Data validated','Cutover planned'],strong_answer_signals:['Data integrity maintained','Minimal downtime'],avoid:['Data loss','No testing']}},
    {id:'de_011',text:'How do you implement data governance?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Data catalog','Metadata management','Stewardship','Policies'],strong_answer_signals:['Governance framework in place'],avoid:['No governance','Data silos']}},
    {id:'de_012',text:'How do you design a real-time analytics architecture?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Streaming source','Stream processing','Warehouse updated','Dashboards served'],strong_answer_signals:['Near real-time insights'],avoid:['Batch only','High latency']}},
    {id:'de_013',text:'How do you handle schema drift in streaming data?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Schema registry','Compatibility checks','Alerting','Handling strategies'],strong_answer_signals:['Drift handled gracefully'],avoid:['Pipeline breaks','No registry']}},
    {id:'de_014',text:'Describe your experience with cloud data platforms.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['AWS/Azure/GCP services','Data lake architecture','Serverless processing','Cost optimization'],strong_answer_signals:['Multi-service solutions','Cost aware'],avoid:['Single service only','No cost management']}},
    {id:'de_015',text:'Tell me about a time you had to explain data concepts to non-technical stakeholders.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Simplified concepts','Business context','Visual aids','Recommendations'],strong_answer_signals:['Stakeholder understood'],avoid:['Too technical','No context']}},
    {id:'de_016',text:'How do you implement data observability?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Freshness monitoring','Volume monitoring','Schema monitoring','Custom checks'],strong_answer_signals:['Observability platform in place'],avoid:['No monitoring','Issues late']}},
    {id:'de_017',text:'How do you handle big data performance optimization?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Data partitioning','Cluster tuning','Caching','Query optimization'],strong_answer_signals:['Performance improved'],avoid:['No tuning','Over-provisioned']}},
    {id:'de_018',text:'Tell me about disagreeing with an analyst about data needs.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Understood the use case','Presented data capabilities','Compromise reached'],strong_answer_signals:['Collaborative solution'],avoid:['Just said no','Ignored analyst']}},
    {id:'de_019',text:'How do you design an ETL vs ELT approach?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Data volume','Transformation complexity','Warehouse capability','Maintenance'],strong_answer_signals:['Right approach chosen'],avoid:['Always ETL','No analysis']}},
    {id:'de_020',text:'How do you handle data residency and localization?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Data classification by region','Storage location rules','Transfer mechanisms','Compliance verification'],strong_answer_signals:['Respected data laws'],avoid:['No regional considerations']}},
    {id:'de_021',text:'Describe your experience with data mesh or lakehouse.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Domain ownership','Data products','Self-serve architecture','Governance'],strong_answer_signals:['Decentralized but governed'],avoid:['Centralized bottleneck','No governance']}},
    {id:'de_022',text:'How do you implement data versioning and reproducibility?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Data versioning tools','Lineage tracking','Reproducible pipelines','Audit trail'],strong_answer_signals:['Reproducible results'],avoid:['No versioning','No lineage']}},
    {id:'de_023',text:'Tell me about building a data product for internal stakeholders.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Identified need','Built the product','User adoption','Iterated'],strong_answer_signals:['Widely adopted','Solved real problem'],avoid:['Built and nobody used']}},
    {id:'de_024',text:'Why data engineering? What keeps you in this field?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Data as foundation','Building infrastructure','Problem solving','Growing demand'],strong_answer_signals:['Specific project story','Continuous learning'],avoid:['Only about money','No interest']}},
    {id:'de_025',text:'How do you design a data platform for machine learning?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Feature store','Training-serving consistency','Experiment tracking','Model registry'],strong_answer_signals:['MLOps pipeline'],avoid:['No feature store','Training-serving skew']}},
    {id:'de_026',text:'How do you implement CI/CD for data pipelines?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Version control for data','Automated testing','Deployment pipeline','Rollback'],strong_answer_signals:['CI/CD in place'],avoid:['Manual deployment','No testing']}},
    {id:'de_027',text:'Tell me about a time you had to optimize data costs.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Analyzed costs','Identified waste','Optimized storage and compute','Measured savings'],strong_answer_signals:['Costs reduced significantly'],avoid:['No cost monitoring','Overspending']}},
    {id:'de_028',text:'How do you handle unstructured data?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Storage design','Processing approach','Schema-on-read','Indexing'],strong_answer_signals:['Efficient processing'],avoid:['Treated like structured']}},
    {id:'de_029',text:'How do you implement data catalog and metadata management?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Catalog tool','Metadata collection','Data lineage','Search capability'],strong_answer_signals:['Catalog adopted'],avoid:['No catalog','No metadata']}},
    {id:'de_030',text:'Tell me about a cross-functional data project.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Multiple teams involved','Shared goals','Data contracts','Project delivered'],strong_answer_signals:['Cross-team success'],avoid:['Single team','Data silos']}},
    {id:'de_031',text:'How do you design disaster recovery for data systems?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Backup strategy','RTO/RPO defined','Failover tested','Documentation'],strong_answer_signals:['Recovery tested'],avoid:['No backup','No recovery plan']}},
    {id:'de_032',text:'How do you evaluate a new data tool or technology?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Use case fit','Scalability','Integration','Cost'],strong_answer_signals:['Data-driven evaluation'],avoid:['Hype-driven','No evaluation']}},
    {id:'de_033',text:'How do you implement data security by design?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Privacy by design','Encryption','Access control','Audit logging'],strong_answer_signals:['Security embedded'],avoid:['Security bolted on later']}},
    {id:'de_034',text:'Tell me about a time you led a data platform migration.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Migration strategy','Data validated','Minimal downtime','Team managed'],strong_answer_signals:['Seamless migration'],avoid:['Data loss','Downtime']}},
    {id:'de_035',text:'What is your approach to data modeling best practices?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Normalization','Performance considerations','Maintenance','Evolution'],strong_answer_signals:['Balanced model'],avoid:['Over-normalized','No performance thought']}}
  ]
};

// ===== UX/UI DESIGN (30 questions) =====
const uxUI = {
  metadata: { sector: 'UX/UI Design', generated: '2026-08-30', total: 30, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'ux_001',text:'Tell me about a redesign you led. What was the approach?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Research conducted','Pain points identified','Design validated','Metrics improved'],strong_answer_signals:['Data-driven redesign','User tested'],avoid:['Design by opinion','No testing']}},
    {id:'ux_002',text:'How do you conduct usability testing?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Task design','Participant recruiting','Moderation','Observations recorded'],strong_answer_signals:['Actionable insights','Real user participants'],avoid:['Testing with teammates','No observations']}},
    {id:'ux_003',text:'How do you handle engineering saying they cannot implement your design?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Explained design intent','Explored alternatives','Simplified solution'],strong_answer_signals:['Collaboration maintained'],avoid:['Insisted on original','Complained']}},
    {id:'ux_004',text:'Describe your design thinking process for a new product.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Empathize','Define','Ideate','Prototype','Test'],strong_answer_signals:['User-centered approach'],avoid:['Skipped research','No testing']}},
    {id:'ux_005',text:'How do you establish a design system?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Component library','Tokens','Accessibility','Documentation','Governance'],strong_answer_signals:['Design system adopted'],avoid:['Inconsistent UI','No documentation']}},
    {id:'ux_006',text:'Tell me about a time you received harsh feedback on your design.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Listened','Understood concern','Revised','Outcome improved'],strong_answer_signals:['Opened to feedback','Improved design'],avoid:['Defensive','Ignored feedback']}},
    {id:'ux_007',text:'How do you measure the impact of a design change?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Metrics before and after','A/B test','User feedback','Business impact'],strong_answer_signals:['Measurable improvement'],avoid:['No measurement','Only opinion']}},
    {id:'ux_008',text:'How do you prioritize features in a design?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['User impact','Business value','Effort','Stakeholder input'],strong_answer_signals:['Clear prioritization'],avoid:['All features','Stakeholder demands only']}},
    {id:'ux_009',text:'How do you ensure accessibility (WCAG) in your designs?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Contrast ratios','Keyboard navigation','Screen reader','Semantic markup'],strong_answer_signals:['WCAG compliance','Audit done'],avoid:['Visual only','No accessibility']}},
    {id:'ux_010',text:'Tell me about a time you had to design for multiple user personas.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Personas defined','Flows adapted','Testing varied','Consistent patterns'],strong_answer_signals:['All personas served'],avoid:['Designed for one user']}},
    {id:'ux_011',text:'How do you create and validate user personas?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Research data','Behavioral patterns','Goals and pain points','Validation'],strong_answer_signals:['Research-backed personas'],avoid:['Made up personas','No data']}},
    {id:'ux_012',text:'How do you handle competing design directions from stakeholders?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Explored all directions','User testing','Data presentation','Decision made'],strong_answer_signals:['Chose based on evidence'],avoid:['Voted by stakeholder','No testing']}},
    {id:'ux_013',text:'Describe your experience with prototyping tools.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Tools used','Fidelity levels','Handoff process','Collaboration'],strong_answer_signals:['Interactive prototypes'],avoid:['Only wireframes','No handoff']}},
    {id:'ux_014',text:'Tell me about a time you had to simplify a complex interface.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Identified complexity','Flow simplified','Progressive disclosure','Testing confirmed'],strong_answer_signals:['Simpler and usable'],avoid:['Removed features','No testing']}},
    {id:'ux_015',text:'Why UX design? What keeps you passionate?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['User empathy','Problem solving','Impact on lives','Craftsmanship'],strong_answer_signals:['Specific user impact story'],avoid:['Only about visuals','No user focus']}},
    {id:'ux_016',text:'How do you conduct competitive UX analysis?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Heuristic evaluation','Benchmarking','Gap analysis','Recommendations'],strong_answer_signals:['Actionable findings'],avoid:['Only screenshots','No analysis']}},
    {id:'ux_017',text:'How do you collaborate with researchers?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Findings synthesized','Design decisions informed','Continuous feedback'],strong_answer_signals:['Research-driven design'],avoid:['Ignored research']}},
    {id:'ux_018',text:'Tell me about a time your design did not work as expected.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Hypothesis tested','Data showed failure','Root cause found','Redesigned'],strong_answer_signals:['Iteration based on data'],avoid:['Blamed users','No iteration']}},
    {id:'ux_019',text:'How do you design for different screen sizes and devices?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Responsive patterns','Breakpoints','Touch targets','Platform conventions'],strong_answer_signals:['Consistent across devices'],avoid:['Desktop only','No touch targets']}},
    {id:'ux_020',text:'How do you handle design handoff to engineering?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Specs and assets','Design tokens','Developer questions addressed','DesignQA'],strong_answer_signals:['Clean handoff'],avoid:['Vague specs','No developer input']}},
    {id:'ux_021',text:'How do you facilitate design workshops?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Agenda set','Stakeholder included','Timeboxed','Action items recorded'],strong_answer_signals:['Productive sessions'],avoid:['No structure','Unfocused']}},
    {id:'ux_022',text:'How do you design for internationalization and localization?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Text expansion','RTL support','Cultural sensitivity','Locale data'],strong_answer_signals:['Multi-language ready'],avoid:['English-only','No localization']}},
    {id:'ux_023',text:'Tell me about influencing product strategy with design.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['User insight discovered','Presented to leadership','Strategy changed','Outcome measured'],strong_answer_signals:['Design shaped strategy'],avoid:['Design ignored','No data']}},
    {id:'ux_024',text:'How do you design for error states and empty states?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Validation messages','Helpful guidance','Empty state illustrations','Recovery actions'],strong_answer_signals:['User never stuck'],avoid:['No error handling','Blank screens']}},
    {id:'ux_025',text:'How do you balance speed and quality in design delivery?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['MVP approach','Iterative design','Core flows first','Polish later'],strong_answer_signals:['Quality maintained'],avoid:['Rushed design','Over-polishing early']}},
    {id:'ux_026',text:'How do you handle design critiques?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Presented intent','Received feedback','Revised','Improved design'],strong_answer_signals:['Open to critique','Design improved'],avoid:['Defensive','Dismissed feedback']}},
    {id:'ux_027',text:'Tell me about building a brand visual identity.',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Brand strategy','Visual language','Design system','Consistent application'],strong_answer_signals:['Cohesive brand identity'],avoid:['No strategy','Inconsistent visuals']}},
    {id:'ux_028',text:'How do you measure design ROI?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Conversion impact','Task completion','Time on task','Support tickets reduced'],strong_answer_signals:['Measurable impact'],avoid:['No ROI measurement']}},
    {id:'ux_029',text:'How do you design for emotional engagement?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Brand personality','Micro-interactions','Delight moments','Feedback'],strong_answer_signals:['Positive emotional response'],avoid:['No personality','Mechanical interaction']}},
    {id:'ux_030',text:'What is your approach to inclusive and accessible design?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Diverse user testing','Assistive technology support','Contrast and sizing','Cognitive load'],strong_answer_signals:['Inclusive by default'],avoid:['Average user only','No accessibility']}}
  ]
};

fs.writeFileSync(dir + '/data_engineering_questions.json', JSON.stringify(dataEng, null, 2));
console.log('Created data_engineering_questions.json with', dataEng.questions.length, 'questions');
fs.writeFileSync(dir + '/ux_ui_questions.json', JSON.stringify(uxUI, null, 2));
console.log('Created ux_ui_questions.json with', uxUI.questions.length, 'questions');
console.log('Total new Tier 1: 35+30 =', dataEng.questions.length + uxUI.questions.length);
