// gen_tier1_b.js - Tier 1 part B: Marketing, Cybersecurity, Product Management
const fs = require('fs');
const dir = 'server/questions';

// ===== MARKETING (30 questions) =====
const marketing = {
  metadata: { sector: 'Marketing & Digital Marketing', generated: '2026-08-30', total: 30, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'mk_001',text:'Tell me about a campaign that failed. What did you learn?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Campaign launched','Metrics disappointed','Root cause identified','Iterated'],strong_answer_signals:['Failed fast','Insights applied'],avoid:['Blamed team','No post-mortem']}},
    {id:'mk_002',text:'How do you define success metrics for a marketing campaign?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Aligned to business goals','KPIs defined upfront','Baseline established','Attribution set'],strong_answer_signals:['SMART metrics','ROI measurable'],avoid:['Vanity metrics only','No baseline']}},
    {id:'mk_003',text:'How do you segment an audience for a targeted campaign?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Demographic and behavioral data','Pain points identified','Personalization strategy','Segments tested'],strong_answer_signals:['Data-driven segments','Conversion improved'],avoid:['One-size-fits-all','No data']}},
    {id:'mk_004',text:'Tell me about aligning marketing with sales on lead quality.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Defined lead scoring','Jointly reviewed criteria','Shared feedback loop','Improved handoff'],strong_answer_signals:['Lead quality improved','Trust built'],avoid:['Blamed sales','Siloed work']}},
    {id:'mk_005',text:'How do you handle a brand crisis on social media?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Acknowledged quickly','Took responsibility','Communicated transparently','Corrective action taken'],strong_answer_signals:['Rapid response','Empathy shown'],avoid:['Deleted comments','Ignored it']}},
    {id:'mk_006',text:'Describe your approach to content marketing strategy.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Audience research','Content pillars defined','Editorial calendar','Distribution plan'],strong_answer_signals:['Content drove traffic','Consistent publishing'],avoid:['No strategy','No distribution']}},
    {id:'mk_007',text:'How do you evaluate ROI for a marketing channel?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Attribution model chosen','CAC calculated','LTV factored','Tested and scaled'],strong_answer_signals:['Channel scaled profitably'],avoid:['Only looked at clicks','No attribution']}},
    {id:'mk_008',text:'Tell me about launching a product with no marketing budget.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Leveraged organic channels','Partnered for co-marketing','Created viral mechanics','Measured traction'],strong_answer_signals:['Zero budget growth','Community built'],avoid:['Waited for budget','Complained']}},
    {id:'mk_009',text:'How do you run an A/B test effectively?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Hypothesis defined','One variable','Statistical significance','Sample size calculated'],strong_answer_signals:['Valid conclusions','Actionable insights'],avoid:['No hypothesis','Peeking early']}},
    {id:'mk_010',text:'How do you prioritize brand building vs performance marketing?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Business stage considered','Short vs long-term','Budget split','Both measured'],strong_answer_signals:['Balanced approach'],avoid:['Ignored one entirely']}},
    {id:'mk_011',text:'Describe your experience with marketing automation.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Platform used','Funnel mapped','Email sequences','Lead nurturing'],strong_answer_signals:['Automation improved efficiency'],avoid:['Bought platform unused','No strategy']}},
    {id:'mk_012',text:'Tell me about a time you disagreed with the CMO or VP of Marketing.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Understood perspective','Presented data-driven alternative','Compromised or convinced'],strong_answer_signals:['Respectful disagreement','Outcome achieved'],avoid:['Public confrontation','Resigned']}},
    {id:'mk_013',text:'How do you approach competitive analysis for a product launch?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Competitors identified','Positioning analyzed','Differentiation found','Positioning defined'],strong_answer_signals:['Clear positioning'],avoid:['No competitor analysis','No differentiation']}},
    {id:'mk_014',text:'How do you build a marketing strategy from scratch for a new product?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Market research','Target persona','Positioning','Channel strategy','KPIs'],strong_answer_signals:['Complete strategy','Stakeholder buy-in'],avoid:['No research','No KPIs']}},
    {id:'mk_015',text:'Tell me about pivoting your marketing strategy mid-campaign.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Recognized need to pivot','Data triggered pivot','Communicated to stakeholders','New approach executed'],strong_answer_signals:['Agile response','Data-backed pivot'],avoid:['Stuck on failing plan']}},
    {id:'mk_016',text:'How do you handle creative disagreements with the design team?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Shared the brief','Respected design expertise','Focused on user needs','Data-informed decisions'],strong_answer_signals:['Collaborative process'],avoid:['Overruled without reason','Micromanaged design']}},
    {id:'mk_017',text:'Describe your approach to SEO strategy.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Keyword research','Content optimization','Technical SEO','Link building','Performance tracking'],strong_answer_signals:['Organic traffic grew'],avoid:['Keyword stuffing','Black hat tactics']}},
    {id:'mk_018',text:'How do you measure brand awareness?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Aided and unaided recall','Share of voice','Direct traffic','Social mentions'],strong_answer_signals:['Multiple signals tracked'],avoid:['Only impressions','Vanity metrics']}},
    {id:'mk_019',text:'Tell me about a cross-functional campaign you led.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Aligned product, sales, marketing','Shared timeline','Regular syncs','Campaign launched'],strong_answer_signals:['Cross-team collaboration'],avoid:['Marketing only','No alignment']}},
    {id:'mk_020',text:'Why marketing? What keeps you in this field?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Impact on business','Creative expression','Data-driven decisions','Constant evolution'],strong_answer_signals:['Specific campaign stories','Always learning'],avoid:['Only about title','No specific interest']}},
    {id:'mk_021',text:'How do you approach demand generation vs lead generation?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Top-of-funnel awareness','Middle nurture','Bottom conversion','Full-funnel view'],strong_answer_signals:['Funnel mapped','Pipeline impact shown'],avoid:['Only did lead gen','No full-funnel view']}},
    {id:'mk_022',text:'How do you handle underperforming paid ads?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Audited targeting and creative','Checked attribution','Optimized bids','Paused or scaled'],strong_answer_signals:['Data-driven decisions'],avoid:['Let it run wasting budget']}},
    {id:'mk_023',text:'Tell me about building a brand from scratch.',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Defined brand purpose','Visual identity','Voice and tone guidelines','Consistent application','Internal buy-in'],strong_answer_signals:['Clear brand identity'],avoid:['No brand guidelines','Inconsistent messaging']}},
    {id:'mk_024',text:'Describe your experience with marketing analytics and dashboards.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Tools used (GA, Mixpanel)','Dashboards built','Attribution models','Insights communicated'],strong_answer_signals:['Data-informed decisions'],avoid:['No analytics','Dashboard unused']}},
    {id:'mk_025',text:'How do you ensure marketing campaigns comply with regulations (GDPR, CAN-SPAM)?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Legal requirements understood','Consent mechanisms','Data handling policy','Regular audits'],strong_answer_signals:['Compliance verified','Privacy respected'],avoid:['Ignored regulations']}},
    {id:'mk_026',text:'Tell me about turning around a negative customer perception.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Identified the perception gap','Listened to feedback','Changed messaging or product','Measured improvement'],strong_answer_signals:['Customer trust restored'],avoid:['Dismissed feedback','Blamed customers']}},
    {id:'mk_027',text:'How do you decide which social media channels to focus on?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Audience presence','Platform strengths','Resource availability','Competitor presence'],strong_answer_signals:['Focused on right channels','Results tracked'],avoid:['On every platform','FOMO-driven']}},
    {id:'mk_028',text:'How do you build an email marketing strategy?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Segmentation','Personalization','Timing optimization','A/B testing subject lines','Unsubscribe handling'],strong_answer_signals:['High open and click rates','Low unsubscribe'],avoid:['Blast emails to all']}},
    {id:'mk_029',text:'Tell me about a time you had to do more with less in marketing.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Audit existing resources','Repurposed content','Automated processes','Leveraged partnerships'],strong_answer_signals:['Creative resourcefulness'],avoid:['Complained about budget','Did nothing']}},
    {id:'mk_030',text:'What is your approach to integrated marketing communications?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Unified messaging','Channel coordination','Consistent brand voice','Measurement across channels'],strong_answer_signals:['Seamless customer experience'],avoid:['Each channel different message']}}
  ]
};

// ===== CYBERSECURITY (35 questions) =====
const cybersecurity = {
  metadata: { sector: 'Cybersecurity / Information Security', generated: '2026-08-30', total: 35, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'cs_001',text:'Tell me about a security incident you handled. What was the impact and how did you respond?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Incident detected','Contained and eradicated','Communicated to stakeholders','Post-incident review'],strong_answer_signals:['Rapid response','Process followed','Lessons learned'],avoid:['Covered up','No post-mortem']}},
    {id:'cs_002',text:'How do you conduct a risk assessment for a new application?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Threat modeling','Vulnerability identification','Risk scoring','Mitigation plan'],strong_answer_signals:['Structured approach','Prioritized by risk'],avoid:['No threat model','No mitigation plan']}},
    {id:'cs_003',text:'How do you implement a zero trust architecture?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Verify every access request','Least privilege access','Micro-segmentation','Continuous monitoring'],strong_answer_signals:['Phased implementation','Measurable improvement'],avoid:['Trusted internal network','No monitoring']}},
    {id:'cs_004',text:'Tell me about a time you identified a vulnerability before it was exploited.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Vulnerability scan or pentest','Risk prioritized','Remediation plan','Verified fix'],strong_answer_signals:['Proactive discovery','No breach occurred'],avoid:['Found after breach','No patching']}},
    {id:'cs_005',text:'How do you handle a developer refusing to fix a security issue?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Explained business risk','Escalated through channels','Found workaround if needed','Documented decision'],strong_answer_signals:['Risk communicated','Business accepted'],avoid:['Dropped it','Bypassed process']}},
    {id:'cs_006',text:'Describe your approach to security awareness training.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Phishing simulations','Role-based training','Regular frequency','Measured effectiveness'],strong_answer_signals:['Phishing click rate dropped','Incidents reduced'],avoid:['Annual slide deck only','No measurement']}},
    {id:'cs_007',text:'How do you perform a penetration test?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Scope defined','Reconnaissance','Vulnerability scanning','Exploitation','Reporting'],strong_answer_signals:['Methodical approach','Actionable findings'],avoid:['Just ran a scanner','No report']}},
    {id:'cs_008',text:'Tell me about implementing an incident response plan.',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Plan written and approved','Team roles defined','Tabletop exercises','Plan tested and updated'],strong_answer_signals:['Plan was actionable','Response improved'],avoid:['Plan on paper only','No exercises']}},
    {id:'cs_009',text:'How do you secure cloud infrastructure?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Identity and access management','Network security groups','Encryption at rest and in transit','Monitoring and alerting'],strong_answer_signals:['Cloud-native security used','Regular audits'],avoid:['Default configurations','No monitoring']}},
    {id:'cs_010',text:'How do you manage secrets and credentials in an organization?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Secrets manager used','No hardcoded secrets','Rotation policy','Access control'],strong_answer_signals:['Centralized secrets','Audit trail'],avoid:['Passwords in code','No rotation']}},
    {id:'cs_011',text:'Tell me about balancing security and user experience.',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Risk assessment','Progressive security','User testing','Measured friction'],strong_answer_signals:['Security without excessive friction'],avoid:['Maximum security always','No UX consideration']}},
    {id:'cs_012',text:'How do you implement identity and access management (IAM)?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Role-based access control','Principle of least privilege','Multi-factor authentication','Access reviews'],strong_answer_signals:['Least privilege enforced','Audit trail'],avoid:['Everyone admin','No MFA']}},
    {id:'cs_013',text:'Tell me about conducting a security audit.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Scope defined','Evidence collected','Findings documented','Remediation tracked'],strong_answer_signals:['Comprehensive audit','Clear findings'],avoid:['Surface level only','No follow-up']}},
    {id:'cs_014',text:'How do you stay current with emerging threats?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Threat intelligence feeds','CVE monitoring','Security conferences','Bug bounty programs'],strong_answer_signals:['Specific sources named','Vulnerability reported'],avoid:['Only learned after breach','No continuous learning']}},
    {id:'cs_015',text:'How do you handle a data breach notification requirement?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Legal timeline understood','Stakeholder notification','Regulatory compliance','Communication plan'],strong_answer_signals:['Timely notification','Compliance verified'],avoid:['Delayed notification','No legal review']}},
    {id:'cs_016',text:'Tell me about implementing a SIEM solution.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Log sources identified','Alert thresholds set','False positive tuned','Response workflows'],strong_answer_signals:['Alerts actionable','MTTD improved'],avoid:['Too many false positives','Logs without analysis']}},
    {id:'cs_017',text:'How do you approach application security (AppSec) in the SDLC?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Shift left approach','SAST and DAST integrated','Security code review','Dependency scanning'],strong_answer_signals:['Security in CI/CD','Vulnerabilities caught early'],avoid:['Security only at the end','Only manual review']}},
    {id:'cs_018',text:'Tell me about influencing security culture across the organization.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Leadership buy-in','Training program','Metrics tracked','Culture improved'],strong_answer_signals:['Security awareness rose','Incidents decreased'],avoid:['Training only','No metrics']}},
    {id:'cs_019',text:'How do you handle third-party vendor security risk?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Vendor assessment','Security questionnaire','Contractual requirements','Ongoing monitoring'],strong_answer_signals:['Risk assessed','Regular reviews'],avoid:['No vendor assessment','Set and forgot']}},
    {id:'cs_020',text:'Describe your experience with compliance frameworks (SOC 2, ISO 27001, HIPAA).',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Requirements mapped','Controls implemented','Evidence collected','Audit passed'],strong_answer_signals:['Certification achieved'],avoid:['No mapping','Audit failed']}},
    {id:'cs_021',text:'Why cybersecurity? What draws you to the field?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Protection mission','Continuous challenge','Growing demand','Ethical purpose'],strong_answer_signals:['Specific incident story','Continuous learning drive'],avoid:['Only about money','No specific interest']}},
    {id:'cs_022',text:'How do you implement network segmentation?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Zone design','Access control lists','Micro-segmentation','Monitoring between zones'],strong_answer_signals:['Lateral movement prevented'],avoid:['Flat network','No monitoring']}},
    {id:'cs_023',text:'Tell me about a time you had to make an ethical decision in security.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Ethical dilemma identified','Stakeholders consulted','Decision aligned with values'],strong_answer_signals:['Ethical choice made','Trust maintained'],avoid:['Cut corners','Ignored ethics']}},
    {id:'cs_024',text:'How do you evaluate a new security tool?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Use case defined','Proof of concept','Integration assessment','ROI analysis'],strong_answer_signals:['Data-driven evaluation'],avoid:['Following trends','No evaluation']}},
    {id:'cs_025',text:'How do you handle encryption key management?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Key lifecycle management','Rotation schedule','Access control','Backup and recovery'],strong_answer_signals:['Policy followed','Key recovery tested'],avoid:['Hardcoded keys','No backup']}},
    {id:'cs_026',text:'Tell me about your experience with threat modeling.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['STRIDE or similar','Data flow mapping','Trust boundaries','Mitigation plan'],strong_answer_signals:['Threat model produced','Controls matched threats'],avoid:['No structured approach']}},
    {id:'cs_027',text:'How do you conduct a vulnerability management program?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Discovery and cataloging','Risk-based prioritization','Remediation SLAs','Reporting to stakeholders'],strong_answer_signals:['Vulnerabilities tracked','SLAs met'],avoid:['Scanned but no remediation','No reporting']}},
    {id:'cs_028',text:'Tell me about leading a security project across multiple teams.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Project scope defined','Cross-team coordination','Regular updates','Project delivered'],strong_answer_signals:['Multiple teams aligned','Project completed'],avoid:['Single team only','Project stalled']}},
    {id:'cs_029',text:'How do you implement secure DevOps (DevSecOps)?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Security integrated into CI/CD','Automated security testing','Shift left culture','Metrics and dashboards'],strong_answer_signals:['Security automated in pipeline','Team adopted'],avoid:['Security only at the end']}},
    {id:'cs_030',text:'How do you handle privacy regulations (GDPR, CCPA)?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Data inventory and mapping','Consent mechanisms','Data subject rights process','DPO coordination'],strong_answer_signals:['Compliance achieved','User rights honored'],avoid:['No data inventory','Ignored user requests']}},
    {id:'cs_031',text:'Tell me about communicating security risk to non-technical leadership.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Translated technical risk to business impact','Prioritized with data','Recommended investment'],strong_answer_signals:['Leadership acted on risk','Budget approved'],avoid:['Too technical','No recommendation']}},
    {id:'cs_032',text:'Describe your approach to security architecture review.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Architecture documentation review','Threat analysis','Control verification','Residual risk assessment'],strong_answer_signals:['Comprehensive review','Actionable findings'],avoid:['Shallow review','No follow-up']}},
    {id:'cs_033',text:'How do you implement a bug bounty or responsible disclosure program?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Scope defined','Reporting channel','Triaging process','Reward and recognition'],strong_answer_signals:['Vulnerabilities found ethically','Researchers engaged'],avoid:['No program','Legal threats to researchers']}},
    {id:'cs_034',text:'How do you ensure supply chain security?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Software bill of materials','Dependency scanning','Vendor assessment','Provenance verification'],strong_answer_signals:['SBOM maintained','Supply chain risks identified'],avoid:['No SBOM','Unverified dependencies']}},
    {id:'cs_035',text:'What is your approach to security governance and policy development?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Policy framework','Stakeholder input','Regular review cycle','Enforcement mechanism'],strong_answer_signals:['Policies adopted','Compliance measured','Regular updates'],avoid:['Policies on paper only','No enforcement']}}
  ]
};

// ===== PRODUCT MANAGEMENT (30 questions) =====
const productMgmt = {
  metadata: { sector: 'Product Management', generated: '2026-08-30', total: 30, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'pmg_001',text:'Tell me about a product you launched from scratch. What was your role?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Idea validated','Roadmap defined','Cross-functional team led','Metrics tracked'],strong_answer_signals:['Shipped successfully','User adoption measured'],avoid:['Vague role','No metrics']}},
    {id:'pmg_002',text:'How do you prioritize features when everything is high priority?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Impact vs effort','User pain points','Business value','Stakeholder alignment'],strong_answer_signals:['Clear rationale','Framework used'],avoid:['No framework','All high priority']}},
    {id:'pmg_003',text:'How do you handle conflicting feedback from stakeholders?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Synthesized feedback','User research data','Weighted decisions','Communicated trade-offs'],strong_answer_signals:['Data-backed decision'],avoid:['Picked one arbitrarily','Ignored feedback']}},
    {id:'pmg_004',text:'Describe your approach to discovering user needs.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['User interviews','Surveys','Analytics review','Competitive research'],strong_answer_signals:['Clear user personas','Insights drove roadmap'],avoid:['No user research']}},
    {id:'pmg_005',text:'Tell me about a product failure. What did you learn?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Product launched','Metrics disappointed','Root cause found','Iteration planned'],strong_answer_signals:['Learned from failure','Iteration planned'],avoid:['Blamed team','No iteration']}},
    {id:'pmg_006',text:'How do you write a product requirements document?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Problem statement','User stories','Acceptance criteria','Success metrics'],strong_answer_signals:['Clear scope','Measurable outcomes'],avoid:['Vague requirements','No acceptance criteria']}},
    {id:'pmg_007',text:'How do you define success metrics for a product?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['North star metric','Guardrail metrics','Leading and lagging indicators','Cohort analysis'],strong_answer_signals:['SMART metrics','North star defined'],avoid:['Vanity metrics','Too many KPIs']}},
    {id:'pmg_008',text:'Tell me about a time you had to kill a product feature.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Data showed low adoption','Decision to sunset','Communication plan','User migration'],strong_answer_signals:['Data-driven decision','User communication'],avoid:['Kept dead feature','No communication']}},
    {id:'pmg_009',text:'How do you conduct competitive analysis?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Feature comparison','Positioning','Pricing','Market share'],strong_answer_signals:['Clear differentiation'],avoid:['No analysis','Copy competitors']}},
    {id:'pmg_010',text:'How do you work with engineering to set realistic timelines?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Break down epics','Estimate with engineering','Buffer for unknowns','Scope negotiation'],strong_answer_signals:['Realistic timelines','Trust built'],avoid:['Imposed deadlines']}},
    {id:'pmg_011',text:'Describe your experience with A/B testing.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Hypothesis','Test design','Statistical significance','Decision criteria'],strong_answer_signals:['Data-driven decisions','Statistical rigor'],avoid:['No hypothesis','Peeking early']}},
    {id:'pmg_012',text:'Tell me about influencing executive decision-making.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Presented data','Clear recommendation','Stakeholder buy-in','Outcome achieved'],strong_answer_signals:['Influenced strategy','Data-backed'],avoid:['No data','No follow-up']}},
    {id:'pmg_013',text:'How do you handle a product that is not meeting its goals?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Diagnosed the gap','Root cause analysis','Pivot or persevere','Communication'],strong_answer_signals:['Honest assessment','Action plan'],avoid:['Denied the problem','Blamed external factors']}},
    {id:'pmg_014',text:'How do you manage a product roadmap?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Outcome-based themes','Quarterly planning','Flexibility','Stakeholder communication'],strong_answer_signals:['Clear themes','Stakeholder aligned'],avoid:['Feature list only','No flexibility']}},
    {id:'pmg_015',text:'Why product management? What keeps you going?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Impact on users','Cross-functional leadership','Problem solving','Continuous learning'],strong_answer_signals:['Specific product story'],avoid:['Only about title','No user impact']}},
    {id:'pmg_016',text:'How do you validate a product idea before building?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Problem interviews','Landing page test','Concierge MVP','Demand signal'],strong_answer_signals:['Validated demand','Iterated quickly'],avoid:['Built without validation']}},
    {id:'pmg_017',text:'How do you define and measure product-market fit?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Retention metrics','Willingness to recommend','Organic growth','Customer interviews'],strong_answer_signals:['PMF signal identified','Metrics improved'],avoid:['No PMF definition']}},
    {id:'pmg_018',text:'Tell me about managing a product across multiple platforms.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Platform differences assessed','Unified experience','Platform-specific features','Consistent metrics'],strong_answer_signals:['Cross-platform coherence'],avoid:['Treated each platform separately']}},
    {id:'pmg_019',text:'How do you handle scope creep in a sprint?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Accept vs defer vs drop','Impact on velocity','Communicated to team','Documented'],strong_answer_signals:['Scope managed'],avoid:['Accepted everything']}},
    {id:'pmg_020',text:'Describe your experience with pricing strategy.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Value-based pricing','Willingness to pay','Competitive pricing','Tiered plans'],strong_answer_signals:['Revenue impact positive'],avoid:['Cost-plus only','No research']}},
    {id:'pmg_021',text:'How do you use data to drive product decisions?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Analytics tools','Funnel analysis','Cohort analysis','Experimentation'],strong_answer_signals:['Data-informed','Not data-dictated'],avoid:['No data','Vanity metrics only']}},
    {id:'pmg_022',text:'Tell me about saying no to a valuable stakeholder.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Understood the request','Presented trade-offs','Offered alternatives','Maintained relationship'],strong_answer_signals:['Stakeholder understood'],avoid:['Just said no','Damaged relationship']}},
    {id:'pmg_023',text:'How do you approach user research on a tight timeline?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Rapid interviews','Surveys','Heuristic evaluation','Existing data'],strong_answer_signals:['Fast insights','Actionable'],avoid:['No research','Took too long']}},
    {id:'pmg_024',text:'How do you align product vision with company strategy?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Company OKRs mapped','Product vision articulated','Team alignment','Quarterly check-ins'],strong_answer_signals:['Vision aligned with strategy'],avoid:['Disconnected vision']}},
    {id:'pmg_025',text:'Describe your experience with technical products.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Technical depth','Engineering partnership','Architecture understanding','Trade-off negotiation'],strong_answer_signals:['Technical credibility','Engineering trust'],avoid:['No technical understanding']}},
    {id:'pmg_026',text:'How do you handle metrics that show a feature is not working?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Validated data quality','Hypothesis tested','Iteration or sunset'],strong_answer_signals:['Data-driven action','No attachment to feature'],avoid:['Ignored metrics']}},
    {id:'pmg_027',text:'Tell me about building a product team from scratch.',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Roles defined','Hiring plan','Culture set','Processes established'],strong_answer_signals:['Team productive quickly'],avoid:['No structure','Hired wrong people']}},
    {id:'pmg_028',text:'How do you decide what to build next?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['User pain','Business value','Effort','Strategic fit'],strong_answer_signals:['Clear prioritization'],avoid:['No framework','Stakeholder demands only']}},
    {id:'pmg_029',text:'How do you measure customer satisfaction (CSAT, NPS)?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Survey design','Timing','Segmentation','Action on feedback'],strong_answer_signals:['Scores tracked','Actions taken'],avoid:['Survey only','No action']}},
    {id:'pmg_030',text:'What is your approach to product lifecycle management?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Introduction strategy','Growth optimization','Maturity planning','Sunset strategy'],strong_answer_signals:['Full lifecycle planned'],avoid:['Only launch phase','No sunset plan']}}
  ]
};

fs.writeFileSync(dir + '/marketing_questions.json', JSON.stringify(marketing, null, 2));
console.log('Created marketing_questions.json with', marketing.questions.length, 'questions');
fs.writeFileSync(dir + '/cybersecurity_questions.json', JSON.stringify(cybersecurity, null, 2));
console.log('Created cybersecurity_questions.json with', cybersecurity.questions.length, 'questions');
fs.writeFileSync(dir + '/product_management_questions.json', JSON.stringify(productMgmt, null, 2));
console.log('Created product_management_questions.json with', productMgmt.questions.length, 'questions');
console.log('Subtotal: 30+35+30 =', marketing.questions.length + cybersecurity.questions.length + productMgmt.questions.length);
