// gen_tier2.js - Tier 2 sector question bank generator for PlacedAI
// Run: node gen_tier2.js
const fs = require('fs');
const dir = 'server/questions';

// ===== CLOUD ENGINEERING / DEVOPS (35 questions) =====
const cloudDevops = {
  metadata: { sector: 'Cloud Engineering / DevOps', generated: '2026-08-30', total: 35, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'cd_001',text:'Tell me about a production outage you helped resolve. What was your role?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Incident detected quickly','Root cause identified','Fix implemented','Post-mortem followed'],strong_answer_signals:['Clear communication','Blameless post-mortem','Prevention measures'],avoid:['Blame on others','No follow-up']}},
    {id:'cd_002',text:'How do you design infrastructure as code (Terraform, CloudFormation)?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Modular and reusable modules','State management','Version control','DRY principles'],strong_answer_signals:['Production-grade patterns','Reviewed and tested'],avoid:['Copy-paste modules','No state locking']}},
    {id:'cd_003',text:'How do you implement a CI/CD pipeline from scratch?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Build, test, deploy stages','Artifact management','Approval gates','Rollback capability'],strong_answer_signals:['Fast and reliable','Zero-downtime deploys','Pipeline as code'],avoid:['Manual steps','No rollback','No tests']}},
    {id:'cd_004',text:'Tell me about implementing Kubernetes in production.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Cluster provisioned','Workloads migrated','Monitoring and logging set up','Team trained'],strong_answer_signals:['Smooth migration','High availability','Team productive'],avoid:['Big-bang migration','No documentation','Team not trained']}},
    {id:'cd_005',text:'How do you handle a security incident in cloud infrastructure?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Incident response process','Forensics conducted','Affected systems isolated','Communication coordinated'],strong_answer_signals:['Quick containment','Thorough investigation','Lessons learned'],avoid:['Panic','No communication','Blame on team']}},
    {id:'cd_006',text:'How do you optimize cloud costs?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Right-sizing instances','Reserved capacity planning','Idle resource cleanup','Storage tiering'],strong_answer_signals:['Significant cost reduction','Continuous monitoring','Tagged resources'],avoid:['Over-provisioned','No tagging','Ignored costs']}},
    {id:'cd_007',text:'Describe your experience with monitoring and observability.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Metrics, logs, traces','Alerting strategy','Dashboard design','SLOs defined'],strong_answer_signals:['Proactive issue detection','Clear SLOs','Actionable alerts'],avoid:['Only metrics','Alert fatigue','No SLOs']}},
    {id:'cd_008',text:'Tell me about managing a multi-account or multi-cloud environment.',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Governance strategy','Account structure designed','Cross-account access','Centralized logging'],strong_answer_signals:['Clean separation','Centralized visibility'],avoid:['Account sprawl','No governance']}},
    {id:'cd_009',text:'How do you approach a greenfield cloud architecture project?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Requirements gathered','Well-architected framework','Security and compliance','Cost estimation'],strong_answer_signals:['Documented decisions','Scalable design'],avoid:['Started building without design','No cost estimation']}},
    {id:'cd_010',text:'How do you handle a database migration to the cloud?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Migration strategy chosen','Data validated','Downtime minimized','Rollback plan'],strong_answer_signals:['Zero data loss','Tested thoroughly'],avoid:['No rollback plan','Big-bang cutover']}},
    {id:'cd_011',text:'How do you implement infrastructure security best practices?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Least privilege IAM','Network segmentation','Encryption everywhere','Vulnerability scanning'],strong_answer_signals:['Security by default','Regular audits'],avoid:['Open security groups','No encryption','No scanning']}},
    {id:'cd_012',text:'Tell me about a time you had to debug a complex distributed system issue.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Logs and traces analyzed','Service map used','Root cause found','Fix verified'],strong_answer_signals:['Systematic approach','Cross-team collaboration'],avoid:['Random guessing','No data']}},
    {id:'cd_013',text:'How do you manage secrets in a cloud environment?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Secrets manager used','No hardcoded secrets','Rotation policy','Access control'],strong_answer_signals:['Centralized secrets','Audit logging'],avoid:['Secrets in code','No rotation']}},
    {id:'cd_014',text:'How do you implement auto-scaling?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Metrics-driven','Predictive scaling','Cost considered','Tested scale events'],strong_answer_signals:['Smooth scale events','Cost optimized'],avoid:['Over-scaling','No testing']}},
    {id:'cd_015',text:'Why cloud engineering / DevOps? What draws you to it?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Automation passion','Scale and reliability','Continuous learning','Impact on teams'],strong_answer_signals:['Specific project story','Community involvement'],avoid:['Just about tools','No specific interest']}},
    {id:'cd_016',text:'How do you approach disaster recovery planning?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['RTO and RPO defined','Backup strategy','Failover tested','Runbook documented'],strong_answer_signals:['Tested regularly','Clear ownership'],avoid:['No testing','Undocumented']}},
    {id:'cd_017',text:'Tell me about a time you improved deployment frequency.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Pain points identified','Pipeline improved','Automation added','Measured improvement'],strong_answer_signals:['Faster and safer deploys','Team velocity up'],avoid:['No measurement','Just talked about it']}},
    {id:'cd_018',text:'How do you evaluate a new cloud service or tool?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Use case defined','POC conducted','Cost and lock-in analyzed','Stakeholder input'],strong_answer_signals:['Data-driven decision','Risk assessed'],avoid:['Hype-driven','No analysis']}},
    {id:'cd_019',text:'How do you handle a major incident that spans multiple services?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Incident commander assigned','War room convened','Status updates regular','All-hands debugging'],strong_answer_signals:['Coordinated response','Clear ownership'],avoid:['Confusion','No commander']}},
    {id:'cd_020',text:'Describe your experience with configuration management (Ansible, Chef, Puppet).',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Idempotent playbooks','Version controlled','Tested changes','Used for scale'],strong_answer_signals:['Production usage','Consistent environments'],avoid:['No version control','Manual changes']}},
    {id:'cd_021',text:'How do you implement a service mesh?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Use case defined','Pilot service chosen','Observability added','Gradual rollout'],strong_answer_signals:['Measurable improvement','Team trained'],avoid:['Big-bang rollout','No pilot']}},
    {id:'cd_022',text:'Tell me about a time you had to balance reliability and feature velocity.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Risks discussed','SLOs defined','Trade-offs made','Outcome measured'],strong_answer_signals:['Informed decision','Stakeholder aligned'],avoid:['Ignored reliability','No measurement']}},
    {id:'cd_023',text:'How do you approach logging strategy for microservices?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Structured logs','Centralized storage','Correlation IDs','Retention policy'],strong_answer_signals:['Searchable logs','Trace context'],avoid:['Unstructured logs','No correlation']}},
    {id:'cd_024',text:'How do you manage technical debt in infrastructure code?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Debt visible','Refactoring prioritized','Tech debt sprints','Documentation current'],strong_answer_signals:['Continuous improvement','Team ownership'],avoid:['Ignored debt','Old modules left']}},
    {id:'cd_025',text:'How do you implement policy as code?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Tools like OPA, Sentinel','Policy tested','CI/CD integrated','Continuous compliance'],strong_answer_signals:['Automated compliance','No manual reviews'],avoid:['Policies in docs only','No automation']}},
    {id:'cd_026',text:'Tell me about building a DevOps culture in a traditional organization.',category:'behavioral',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Resistance assessed','Quick wins delivered','Champions identified','Practices spread'],strong_answer_signals:['Culture shifted','Teams adopted'],avoid:['Mandated from top','No quick wins']}},
    {id:'cd_027',text:'How do you design a multi-region deployment?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Active-active vs active-passive','Data replication','Latency considered','Failover tested'],strong_answer_signals:['Resilient design','Tested failover'],avoid:['No testing','Single region assumption']}},
    {id:'cd_028',text:'How do you handle a vendor or cloud provider outage?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Communication plan','Workarounds implemented','Multi-cloud or DR considered','Stakeholders updated'],strong_answer_signals:['Business continuity','Quick adaptation'],avoid:['Single cloud dependency','No plan']}},
    {id:'cd_029',text:'Describe your experience with serverless architectures.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Use cases identified','Cold start managed','Cost monitored','Vendor lock-in considered'],strong_answer_signals:['Production experience','Right tool for job'],avoid:['Serverless for everything','No cost analysis']}},
    {id:'cd_030',text:'How do you implement chaos engineering?',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Hypothesis-driven','Production-safe experiments','Gradually expanded','Findings acted on'],strong_answer_signals:['Resilience improved','Systematic approach'],avoid:['Random failures','No hypothesis']}},
    {id:'cd_031',text:'How do you ensure infrastructure changes are safe?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Code review','Automated tests','Staged rollouts','Rollback ready'],strong_answer_signals:['Few incidents','Quick recovery'],avoid:['No review','Big-bang changes']}},
    {id:'cd_032',text:'Tell me about mentoring junior DevOps engineers.',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Skill assessment','Pair on incidents','Knowledge sharing','Career growth'],strong_answer_signals:['Engineers grew','Team capability up'],avoid:['No mentoring time','No growth']}},
    {id:'cd_033',text:'How do you balance automation vs human review?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Risk-based','Critical changes reviewed','Automation trusted for routine','Clear policy'],strong_answer_signals:['Right balance','Fast and safe'],avoid:['All manual','All automated']}},
    {id:'cd_034',text:'How do you handle capacity planning?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Growth projected','Peak load identified','Headroom planned','Cost analyzed'],strong_answer_signals:['Met demand','Cost optimized'],avoid:['No planning','Last minute scaling']}},
    {id:'cd_035',text:'Tell me about implementing GitOps.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'STAR',key_points:['Git as source of truth','Automated sync','Drift detection','Rollback via Git'],strong_answer_signals:['Improved reliability','Audit trail'],avoid:['No automation','Drift ignored']}}
  ]
};

// ===== HEALTHCARE CLINICAL (30 questions) =====
const healthcareClinical = {
  metadata: { sector: 'Healthcare Clinical (NP, PA, Pharmacy)', generated: '2026-08-30', total: 30, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'hcc_001',text:'Tell me about a time you managed a difficult patient case.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Case complexity assessed','Interdisciplinary collaboration','Patient-centered care','Outcome achieved'],strong_answer_signals:['Comprehensive care','Patient trust built'],avoid:['Dismissed complexity','No collaboration']}},
    {id:'hcc_002',text:'How do you approach medication reconciliation?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Complete medication history','Cross-referenced sources','Patient interview','Discrepancies resolved'],strong_answer_signals:['Errors prevented','Comprehensive review'],avoid:['Rushed review','No patient interview']}},
    {id:'hcc_003',text:'How do you handle a patient who refuses treatment?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Understood patient concerns','Explained risks and benefits','Respected autonomy','Documented decision'],strong_answer_signals:['Patient autonomy respected','Clear documentation'],avoid:['Coerced patient','No documentation']}},
    {id:'hcc_004',text:'Tell me about a time you caught a medication error.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Error identified quickly','Reported appropriately','Patient safety ensured','Process improved'],strong_answer_signals:['Patient safety protected','Systemic fix'],avoid:['Covered up','No process change']}},
    {id:'hcc_005',text:'How do you stay current with clinical guidelines and evidence?',category:'motivation',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Guidelines reviewed','Journals and CME','Peer discussions','Evidence-based practice'],strong_answer_signals:['Specific sources named','Practice updated'],avoid:['Relied on training only','Outdated practice']}},
    {id:'hcc_006',text:'Describe your approach to chronic disease management.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Comprehensive assessment','Patient education','Care plan developed','Outcomes tracked'],strong_answer_signals:['Patient outcomes improved','Coordinated care'],avoid:['Medication only','No follow-up']}},
    {id:'hcc_007',text:'How do you handle a high-pressure clinical situation?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Stayed calm','Used systematic approach','Called for help when needed','Communicated clearly'],strong_answer_signals:['Good outcome','Team coordination'],avoid:['Panicked','No help called']}},
    {id:'hcc_008',text:'Tell me about collaborating with physicians and specialists.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Clear communication','Respected expertise','Patient-focused','Followed through'],strong_answer_signals:['Effective collaboration','Patient care improved'],avoid:['Hierarchical issues','No follow-through']}},
    {id:'hcc_009',text:'How do you approach patient education?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Assessed health literacy','Used teach-back','Provided resources','Family included'],strong_answer_signals:['Patient understood','Adherence improved'],avoid:['Medical jargon','No verification']}},
    {id:'hcc_010',text:'Why healthcare? What keeps you in this field?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Patient impact','Intellectual challenge','Continuous learning','Helping people'],strong_answer_signals:['Specific patient stories','Long-term commitment'],avoid:['Only about money','No specific reason']}},
    {id:'hcc_011',text:'How do you handle ethical dilemmas in clinical practice?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Identified ethical issue','Consulted ethics committee','Considered all stakeholders','Documented reasoning'],strong_answer_signals:['Patient-centered resolution','Clear documentation'],avoid:['Ignored issue','No consultation']}},
    {id:'hcc_012',text:'Tell me about a time you had to deliver bad news to a patient.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Prepared carefully','Used SPIKES protocol','Offered support','Followed up'],strong_answer_signals:['Patient received well','Support provided'],avoid:['Rushed disclosure','No support offered']}},
    {id:'hcc_013',text:'How do you manage your clinical documentation?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Timely documentation','Clear and concise','Compliant with regulations','Used templates wisely'],strong_answer_signals:['Quality documentation','Efficient workflow'],avoid:['Late documentation','Vague notes']}},
    {id:'hcc_014',text:'Describe your experience with EHR systems.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Systems used','Workflow optimization','Template use','Efficiency improvements'],strong_answer_signals:['Improved workflow','Reduced clicks'],avoid:['Struggled with EHR','No optimization']}},
    {id:'hcc_015',text:'How do you approach polypharmacy in elderly patients?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Medication review','Beers criteria applied','Deprescribing considered','Patient goals discussed'],strong_answer_signals:['Reduced medication burden','Patient-centered'],avoid:['Added more medications','No review']}},
    {id:'hcc_016',text:'Tell me about managing a patient with multiple comorbidities.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Comprehensive assessment','Prioritized conditions','Coordinated specialists','Patient goals aligned'],strong_answer_signals:['Coordinated care','Patient quality of life'],avoid:['Siloed treatment','No coordination']}},
    {id:'hcc_017',text:'How do you handle a situation where you do not know the answer?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Admitted uncertainty','Researched or consulted','Followed up with patient','Documented'],strong_answer_signals:['Patient safety first','Honest communication'],avoid:['Made up answer','Did not follow up']}},
    {id:'hcc_018',text:'How do you approach preventive care?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Evidence-based guidelines','Risk assessment','Patient counseling','Follow-up scheduled'],strong_answer_signals:['Preventive services delivered','Patient outcomes improved'],avoid:['Reactive only','No follow-up']}},
    {id:'hcc_019',text:'Tell me about a time you had to advocate for a patient.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Identified patient need','Navigated system','Communicated effectively','Outcome achieved'],strong_answer_signals:['Patient received needed care','Persistent advocacy'],avoid:['Gave up','No outcome']}},
    {id:'hcc_020',text:'How do you approach quality improvement in your practice?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Data reviewed','Improvement identified','PDSA cycles','Measured impact'],strong_answer_signals:['Outcomes improved','Team engagement'],avoid:['No measurement','One-off changes']}},
    {id:'hcc_021',text:'Describe your experience with telehealth.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Platforms used','Patient engagement','Limitations understood','Documentation maintained'],strong_answer_signals:['Effective virtual care','Good outcomes'],avoid:['Phone only','Poor documentation']}},
    {id:'hcc_022',text:'How do you handle cultural differences in patient care?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Cultural humility','Asked about preferences','Adapted approach','Used interpreters when needed'],strong_answer_signals:['Respectful care','Patient trust built'],avoid:['Made assumptions','Dismissed concerns']}},
    {id:'hcc_023',text:'Tell me about a time you had a conflict with a colleague.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Addressed directly','Listened actively','Found common ground','Patient care prioritized'],strong_answer_signals:['Resolved professionally','Working relationship maintained'],avoid:['Avoided conflict','Took sides']}},
    {id:'hcc_024',text:'How do you approach antibiotic stewardship?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Appropriate prescribing','Culture-guided therapy','Patient education','Resistance patterns considered'],strong_answer_signals:['Appropriate use','Patient outcomes preserved'],avoid:['Overprescribing','No culture']}},
    {id:'hcc_025',text:'How do you manage a busy clinic day?',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Time management','Triage approach','Efficient documentation','Team coordination'],strong_answer_signals:['Quality care maintained','Patient satisfaction'],avoid:['Rushed visits','Burnout ignored']}},
    {id:'hcc_026',text:'Tell me about a complex diagnostic case.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Differential diagnosis','Appropriate testing','Specialist consultation','Diagnosis reached'],strong_answer_signals:['Thorough workup','Correct diagnosis'],avoid:['Premature closure','No consultation']}},
    {id:'hcc_027',text:'How do you handle end-of-life discussions?',category:'situational',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Patient and family included','Goals of care discussed','Compassionate communication','Documented'],strong_answer_signals:['Patient dignity respected','Clear goals'],avoid:['Avoided discussion','Dismissive']}},
    {id:'hcc_028',text:'How do you approach continuing education and board certification?',category:'motivation',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['CME completed','Board certified','Learning goals set','Practice improved'],strong_answer_signals:['Current certification','Specific learning'],avoid:['Lapsed certification','No learning']}},
    {id:'hcc_029',text:'Describe your experience with clinical research.',category:'technical',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Studies participated','IRB compliance','Patient safety','Evidence applied'],strong_answer_signals:['Research-informed practice','Patient safety'],avoid:['Protocol deviations','No application']}},
    {id:'hcc_030',text:'How do you handle stress and prevent burnout?',category:'motivation',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Self-care practices','Boundaries set','Support system','Professional help when needed'],strong_answer_signals:['Sustainable practice','Team support'],avoid:['Workaholic mindset','No boundaries']}}
  ]
};

// ===== LEGAL & PARALEGAL (25 questions) =====
const legalParalegal = {
  metadata: { sector: 'Legal & Paralegal', generated: '2026-08-30', total: 25, schema_version: '1.1', categories: ['behavioral', 'manager', 'motivation', 'situational', 'technical'] },
  questions: [
    {id:'lg_001',text:'Tell me about a complex legal matter you worked on.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Matter complexity assessed','Strategy developed','Stakeholders coordinated','Outcome achieved'],strong_answer_signals:['Strong analytical work','Effective strategy'],avoid:['Vague description','No outcome']}},
    {id:'lg_002',text:'How do you conduct legal research?',category:'technical',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Issue framed','Sources identified','Cross-referenced','Memo written'],strong_answer_signals:['Thorough research','Well-organized memo'],avoid:['Relied on one source','No memo']}},
    {id:'lg_003',text:'How do you handle a tight deadline on a legal matter?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Prioritized tasks','Managed scope','Communicated timeline','Delivered quality work'],strong_answer_signals:['On-time delivery','Quality maintained'],avoid:['Missed deadline','No communication']}},
    {id:'lg_004',text:'Tell me about a time you had to maintain client confidentiality.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Confidentiality risk identified','Proper protocols followed','Information protected','Client trust maintained'],strong_answer_signals:['Strict adherence','Trust preserved'],avoid:['Disclosed information','No protocol']}},
    {id:'lg_005',text:'How do you draft a contract or legal document?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Requirements understood','Templates used','Risk identified','Reviewed thoroughly'],strong_answer_signals:['Clear and enforceable','Client protected'],avoid:['Vague language','No review']}},
    {id:'lg_006',text:'How do you handle a conflict of interest?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Conflict identified','Disclosed appropriately','Withdrew or waived','Documented'],strong_answer_signals:['Ethical handling','Clear documentation'],avoid:['Ignored conflict','No disclosure']}},
    {id:'lg_007',text:'Why legal? What drives you in this field?',category:'motivation',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Justice motivation','Analytical interest','Problem solving','Impact on clients'],strong_answer_signals:['Specific motivation','Long-term commitment'],avoid:['Only about money','No specific reason']}},
    {id:'lg_008',text:'Describe your experience with e-discovery.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Tools used','Process followed','Privilege protected','Cost managed'],strong_answer_signals:['Efficient process','No spoliation'],avoid:['Manual review only','Privilege breached']}},
    {id:'lg_009',text:'How do you stay current with legal changes?',category:'motivation',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Continuing legal education','Legal publications','Bar association','Practice updates'],strong_answer_signals:['Specific sources named','Practice informed'],avoid:['No CLE','Outdated knowledge']}},
    {id:'lg_010',text:'Tell me about managing a large caseload.',category:'manager',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Prioritization system','Calendar management','Delegation','Technology used'],strong_answer_signals:['All matters attended','No missed deadlines'],avoid:['Missed deadlines','Overwhelmed']}},
    {id:'lg_011',text:'How do you handle an opposing counsel who is difficult?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Professional demeanor','Focused on issues','Avoided personalization','Escalated when needed'],strong_answer_signals:['Maintained professionalism','Effective negotiation'],avoid:['Took personally','Responded emotionally']}},
    {id:'lg_012',text:'Tell me about a time you had to explain complex legal concepts to a client.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Assessed client knowledge','Used plain language','Visual aids','Verified understanding'],strong_answer_signals:['Client understood','Informed decisions'],avoid:['Used legal jargon','No verification']}},
    {id:'lg_013',text:'How do you approach compliance and regulatory work?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Regulations identified','Gap analysis done','Policies developed','Training provided'],strong_answer_signals:['Compliance achieved','No violations'],avoid:['Box-checking','No training']}},
    {id:'lg_014',text:'Describe your experience with case management software.',category:'technical',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Systems used','Workflow organized','Document management','Billing tracked'],strong_answer_signals:['Efficient workflow','No missed items'],avoid:['Disorganized','No tracking']}},
    {id:'lg_015',text:'How do you handle a pro bono or under-resourced matter?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Resource needs assessed','Creative solutions','Community resources','Quality maintained'],strong_answer_signals:['Client served well','Resources leveraged'],avoid:['Cut corners','Poor outcome']}},
    {id:'lg_016',text:'Tell me about a case you lost. What did you learn?',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Case reviewed','Lessons identified','Practice improved','Honest reflection'],strong_answer_signals:['Practice evolved','Lessons applied'],avoid:['Blamed judge','No learning']}},
    {id:'lg_017',text:'How do you approach document review?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Strategy developed','Tech-assisted review','Quality control','Privilege logged'],strong_answer_signals:['Efficient and accurate','No privilege issues'],avoid:['Slow manual review','Privilege issues']}},
    {id:'lg_018',text:'How do you mentor junior associates or paralegals?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Skill assessment','Training provided','Quality review','Career development'],strong_answer_signals:['Team grew','Quality maintained'],avoid:['No training','High turnover']}},
    {id:'lg_019',text:'Tell me about a time you had to make a difficult ethical decision.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Ethical issue identified','Rules consulted','Decision made','Documented'],strong_answer_signals:['Ethical resolution','Bar compliant'],avoid:['Cut corners','No documentation']}},
    {id:'lg_020',text:'How do you handle client expectations that are unrealistic?',category:'situational',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Set clear expectations early','Educated client','Documented agreement','Managed throughout'],strong_answer_signals:['Client aligned','Trust maintained'],avoid:['Over-promised','Disappointed client']}},
    {id:'lg_021',text:'Describe your experience with litigation support.',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Tools used','Case preparation','Court filings','Discovery managed'],strong_answer_signals:['Effective support','No missed deadlines'],avoid:['Disorganized','Late filings']}},
    {id:'lg_022',text:'How do you approach negotiation?',category:'technical',seniority:['mid','senior'],answer_framework:{structure:'Framework',key_points:['Prepared thoroughly','Understood interests','Created options','BATNA analyzed'],strong_answer_signals:['Successful outcomes','Relationships maintained'],avoid:['Unprepared','Adversarial only']}},
    {id:'lg_023',text:'How do you handle multiple simultaneous deadlines?',category:'situational',seniority:['entry','mid','senior'],answer_framework:{structure:'Framework',key_points:['Prioritized by urgency and importance','Calendar used','Communication maintained','Quality preserved'],strong_answer_signals:['All deadlines met','Quality maintained'],avoid:['Missed deadlines','Rushed work']}},
    {id:'lg_024',text:'Tell me about a successful case or matter outcome.',category:'behavioral',seniority:['mid','senior'],answer_framework:{structure:'STAR',key_points:['Strategy executed','Team coordinated','Outcome favorable','Lessons captured'],strong_answer_signals:['Strong result','Team effort'],avoid:['Self-aggrandizing','No detail']}},
    {id:'lg_025',text:'How do you approach business development in legal practice?',category:'manager',seniority:['senior','manager'],answer_framework:{structure:'Framework',key_points:['Network built','Thought leadership','Client relationships','Referral network'],strong_answer_signals:['Practice grew','Strong relationships'],avoid:['No business development','Relied on firm only']}}
  ]
};

fs.writeFileSync(dir + '/cloud_devops_questions.json', JSON.stringify(cloudDevops, null, 2));
console.log('Created cloud_devops_questions.json with', cloudDevops.questions.length, 'questions');
fs.writeFileSync(dir + '/healthcare_clinical_questions.json', JSON.stringify(healthcareClinical, null, 2));
console.log('Created healthcare_clinical_questions.json with', healthcareClinical.questions.length, 'questions');
fs.writeFileSync(dir + '/legal_paralegal_questions.json', JSON.stringify(legalParalegal, null, 2));
console.log('Created legal_paralegal_questions.json with', legalParalegal.questions.length, 'questions');
console.log('Tier 2 part A: 35+30+25 =', cloudDevops.questions.length + healthcareClinical.questions.length + legalParalegal.questions.length);
